### ISSUE TITLE
Ability to access serializer class

### ISSUE THREAD

**Issue by michaelcapizzi** [myedibleenso/py-processors#1]
It would be helpful to have access to the [Serializer](https://github.com/clulab/processors/blob/37392ced3a0ebdaf0a7481dccf0ce26991820dba/src/main/scala/edu/arizona/sista/utils/Serializer.scala) class from the original `processors` library.

This would help with the annotation time required for large documents.

**Comment by myedibleenso** [comment]
How do you want this to work?  Do you need to load something serialized, serialize something you've annotated, or both?

**Comment by michaelcapizzi** [comment]
I don't think one is very useful without the other.  So ideally, one could `serialize` to text file (similarly to how it's done in `scala`) and then also import that `serialization`.

**Comment by myedibleenso** [comment]
I've added to/from JSON methods to all classes. `processors-server` has utilities for converting this JSON into a `processors.Document`.   Not sure if/when those changes will make it into `processors` though.
